[Output]
Format=sysext
ImageId=podman
ManifestFormat=json
Output=%i_%v_%a
Overlay=yes

[Content]
BaseTrees=%O/base_%v_%a
Packages=
        crun
        distrobox
        passt
        podman
        uidmap

[Validation]
Checksum=yes