[Match]
Architecture=x86-64

[Output]
Format=disk
ImageId=juno
ManifestFormat=json
Output=%i_%v_%a
SplitArtifacts=uki,partitions

[Config]
Profiles=Bootable

[Content]
Initrds=%O/initrd_%v_%a
BaseTrees=%O/base_%v_%a
ExtraTrees=%D/mkosi.extra.bootable
UnifiedKernelImageFormat=%i_%v_%a
RootPassword=hashed:$6$V4bf/bJS/AffGLns$yXmOzf0UU2rijWJoVzLOgIwZmZAu7A9PUVoi8.uSKkvGIry55xRSYAgsAPD0CaPxJy5tY4yviRutFZhPRYpn00
Bootable=yes
KernelCommandLine=
        root=LABEL=root
        mount.usr=dissect
        rd.systemd.mask=systemd-validatefs@sysroot-usr.service
        rw
        audit=0
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=encrypted+absent:swap=encrypted+unused+absent:home=unprotected+absent:=ignore
        systemd.image_filter=usr=juno*:usr-verity=juno*:usr-verity-sig=juno*:root=root:swap=juno-*
        ipe.enforce=0
        systemd.set-credential=agetty.autologin:root
        systemd.set-credential=login.noauth:yes
        SYSTEMD_SULOGIN_FORCE=1
        systemd.journald.forward_to_console=1
        systemd.journald.max_level_console=warning
        #quiet splash vt.global_cursor_default=0 loglevel=0 systemd.show_status=auto rd.udev.log_level=0
KernelInitrdModules=default
Packages=
        linux-image-generic
        firmware-linux

[Config]
Dependencies=initrd
