[Output]
Format=tar
SplitArtifacts=tar
ImageId=base+hypr
Output=%i_%v_%a
ManifestFormat=json

[Content]
BaseTrees=%O/base_%v_%a
Bootable=no
CleanPackageMetadata=no
Packages=
        firefox
        fonts-inter
        fonts-inter-variable
        fonts-jetbrains-mono
        fonts-noto
        fonts-noto-cjk
        fonts-noto-color-emoji
        foot
        fuzzel
        helvum
        hunspell
        hunspell-de-de
        hunspell-en-us
        hypridle
        hyprland
        hyprlock
        hyprpaper
        hyprpolkitagent
        keepassxc-minimal
        libqt5waylandclient5
        libspa-0.2-libcamera
        mako-notifier
        mpd
        network-manager
        orchis-gtk-theme
        pcmanfm
        plattenalbum
        pipewire-audio
        pipewire-alsa
        pulseaudio-utils
        sassc
        swayosd
        thunar
        thunderbird
        uwsm
        waybar
        wireless-regdb
        wtype

[Validation]
Checksum=yes
