[Output]
Format=tar
SplitArtifacts=tar
ImageId=base+hypr
Output=%i_%v_%a
ManifestFormat=json

[Content]
BaseTrees=%O/base_%v_%a
Bootable=no
CleanPackageMetadata=no
Packages=
	mpd
	orchis-gtk-theme
	plattenalbum
	sassc
	thunar
	thunderbird
	uwsm
        firefox
        fonts-inter
        fonts-inter-variable
        fonts-jetbrains-mono
        fonts-noto
        fonts-noto-cjk
        fonts-noto-color-emoji
        foot
        fuzzel
        hunspell
        hunspell-de-de
        hunspell-en-us
        hypridle
        hyprland
        hyprlock
        hyprpaper
        hyprpolkitagent
        keepassxc-minimal
        libqt5waylandclient5
        mako-notifier
	mpd
        network-manager
	plattenalbum
	sassc
	thunar
	thunderbird
	uwsm
        waybar
        wireless-regdb
        wtype

[Validation]
Checksum=yes
