[Output]
Format=tar
SplitArtifacts=tar
ImageId=base+hypr
Output=%i_%v_%a
ManifestFormat=json

[Content]
BaseTrees=%O/base_%v_%a
Bootable=no
CleanPackageMetadata=no
Packages=
        firefox
        fonts-inter
        fonts-inter-variable
        fonts-jetbrains-mono
        fonts-noto
        fonts-noto-cjk
        fonts-noto-color-emoji
        foot
        fuzzel
        hunspell
        hunspell-de-de
        hunspell-en-us
        hypridle
        hyprland
        hyprlock
        hyprpaper
        keepassxc-minimal
        hyprpolkitagent
        network-manager
        waybar
        wireless-regdb
        wtype

[Validation]
Checksum=yes
