[Build]
CacheDirectory=mkosi.cache
History=yes
ToolsTree=yes

[Output]
OutputDirectory=mkosi.output
Format=none

[Distribution]
Distribution=debian
Release=sid
Snapshot=20260402T143026Z
Repositories=non-free-firmware

[Content]
SourceDateEpoch=0

[Runtime]
RuntimeSize=30G
RAM=4G
CPUs=4
Ephemeral=yes

[Validation]
Verity=auto
SecureBoot=no
