[Build]
CacheDirectory=mkosi.cache
History=yes
Incremental=yes
ToolsTree=yes

[Output]
Format=directory
ImageId=atomic
ManifestFormat=json
#Output=%i_%v_%a
Output=%i
OutputDirectory=mkosi.output

[Distribution]
Distribution=debian
Release=sid
Repositories=non-free-firmware
Snapshot=20260312T203005Z

[Config]
Profiles=gnome

[Content]
Autologin=yes
SourceDateEpoch=0
Packages=
        acl
        apt
        attr
        bash-completion
        bpftool
        ca-certificates
        console-setup
        coreutils
        cpio
        cryptsetup-bin
        curl
        dbus-broker
        debian-archive-keyring
        diffutils
        dmidecode
        dosfstools
        e2fsprogs
        efibootmgr
        erofs-utils
        exfatprogs
        fdisk
        fido2-tools
        file
        findutils
        firmware-linux
        fish
        fwupd
        gdb
        gdisk
        git
        grep
        gzip
        iproute2
        iputils-ping
        jq
        kbd
        kexec-tools
        keyboard-configuration
        kmod
        less
        libcap-ng-utils
        libidn2-0
        libmtp-runtime
        libnss-myhostname
        libnss-mymachines
        libnss-systemd
        libpam-pwquality
        libpam-systemd
        libpwquality1
        libqrencode4
        linux-image-generic
        linux-perf
        linux-sysctl-defaults
        login
        man
        manpages
        mtools
        nano
        nftables
        nvme-cli
        opensc
        openssh-client
        openssh-server
        openssl
        p11-kit
        passwd
        patch
        pciutils
        pcsc-tools
        pcscd
        pkcs11-provider
        polkitd
        procps
        python3
        sbsigntool
        sed
        socat
        systemd
        systemd-boot
        systemd-boot-efi
        systemd-boot-efi-signed
        systemd-container
        systemd-coredump
        systemd-cryptsetup
        systemd-repart
        systemd-resolved
        systemd-sysv
        systemd-timesyncd
        systemd-ukify
        systemd-zram-generator
        tar
        tpm2-tools
        tree
        udev
        unzip
        usbutils
        util-linux
        util-linux-extra
        wget
        which
        xfsprogs
        xxd
        xz-utils
        zip
        zstd
# desktop
        bluez
        debconf
        desktop-file-utils
        flatpak
        gstreamer1.0-libav
        gstreamer1.0-plugins-ugly
        kbd
        libsecret-tools
        libyubikey-udev
        locales-all
        mesa-vulkan-drivers
        modemmanager
        network-manager
        pax-utils
        pgpdump
        pipewire-audio
        plymouth
       	plymouth-themes
        steam-devices
        tuned-ppd
        va-driver-all
        wireless-regdb
        wpasupplicant
        xdg-desktop-portal
# apps
        crun
        distrobox
        passt
        podman
        syncthing

[Runtime]
RuntimeSize=30G
RAM=4G
CPUs=4
Ephemeral=yes
QemuArgs=
    -vga std
KernelCommandLineExtra=
        systemd.mask=podman.socket
        systemd.mask=podman-clean-transient.service
        systemd.mask=podman-auto-update.service
        systemd.mask=podman-restart.service
        #systemd.mask=gdm.service

[Validation]
Verity=auto
SecureBoot=no
