[Output]
Format=sysext
ImageId=docker
ManifestFormat=json
Output=%i_%v_%a
Overlay=yes

[Content]
BaseTrees=%O/base_%v_%a
Packages=
        distrobox
        docker-buildx
        docker-cli
        docker-compose
        docker.io

[Validation]
Checksum=yes
