[Content]
Packages=
        akonadi-backend-sqlite
        ark
        bluedevil
        breeze-gtk-theme
        dolphin
        fonts-inter
        fonts-noto
        fonts-noto-cjk
        fonts-noto-color-emoji
        kde-config-gtk-style
        kde-config-sddm
        kde-plasma-desktop
        kde-spectacle
        kgamma
        kinfocenter
        kmail
        konsole
        kscreen
        ksshaskpass
        kwrited
        libpam-kwallet5
        marknote
        ocean-sound-theme
        plasma-desktop
        plasma-disks
        plasma-nm
        plasma-pa
        plasma-systemmonitor
        plasma-thunderbolt
        plasma-welcome
        plasma-workspace-wallpapers
        powerdevil
        sddm
        sddm-theme-breeze
        xdg-desktop-portal-kde
        xdg-desktop-portal-gtk
        xsettings-kde
RemovePackages=
        fonts-cantarell
        xserver-xorg
