[Content]
Packages=
        akonadi-backend-sqlite
        ark
        bluedevil
        breeze-gtk-theme
        dolphin
        kde-config-gtk-style
        kde-config-sddm
        kde-spectacle
        kgamma
        kinfocenter
        kmail
        konsole
        kscreen
        ksshaskpass
        kwrited
        libpam-kwallet5
        ocean-sound-theme
        plasma-desktop
        plasma-disks
        plasma-nm
        plasma-pa
        plasma-systemmonitor
        plasma-thunderbolt
        plasma-welcome
        plasma-workspace-wallpapers
        powerdevil
        sddm
        sddm-theme-breeze
        xdg-desktop-portal-kde