[Output]
Format=tar
SplitArtifacts=tar
ImageId=base+kde
Output=%i_%v_%a
ManifestFormat=json

[Content]
BaseTrees=%O/base_%v_%a
Bootable=no
CleanPackageMetadata=no
Packages=
        accountwizard
        akonadi-backend-sqlite
        ark
        bluedevil
        breeze-gtk-theme
        dolphin
        firefox
        fonts-inter
        fonts-inter-variable
        fonts-jetbrains-mono
        fonts-noto
        fonts-noto-cjk
        fonts-noto-color-emoji
        greetd
        gwenview
        kde-config-gtk-style
        kde-config-sddm
        kde-plasma-desktop
        kde-spectacle
        kgamma
        kinfocenter
        kio-extras
        kmail
        konsole
        kscreen
        ksshaskpass
        kwalletmanager
        kwin-wayland
        kwrite
        kwrited
        libpam-kwallet5
        merkuro
        mpv
        neochat
        ocean-sound-theme
        okular
        plasma-desktop
        plasma-disks
        plasma-nm
        plasma-pa
        plasma-systemmonitor
        plasma-welcome
        plasma-workspace-wallpapers
        powerdevil
        sddm-theme-breeze
        tokodon
        udisks2
        upower
        xdg-desktop-portal-gtk
        xdg-desktop-portal-kde
        xsettings-kde
        yt-dlp
RemovePackages=
        sddm

[Validation]
Checksum=yes
