[Output]
Format=tar
SplitArtifacts=tar
ImageId=base+kde
Output=%i_%v_%a
ManifestFormat=json

[Content]
BaseTrees=%O/base_%v_%a
Bootable=no
CleanPackageMetadata=no
Packages=
        accountwizard
        akonadi-backend-sqlite
        ark
        bluedevil
        breeze-gtk-theme
        cups
        cups-browsed
        cups-pk-helper
        dolphin
        firefox-esr
        fonts-inter
        fonts-inter-variable
        fonts-jetbrains-mono
        fonts-noto
        fonts-noto-cjk
        fonts-noto-color-emoji
        gwenview
        hunspell
        hunspell-de-de
        hunspell-en-us
        itinerary
        kde-config-gtk-style
        kde-config-screenlocker
        kde-config-sddm
        kde-config-updates
        kde-plasma-desktop
        kde-spectacle
        kdeconnect
        kdepim-addons
        kgamma
        kinfocenter
        kio-extras
        kmail
        konsole
        kscreen
        ksshaskpass
        ksshaskpass
        kwalletmanager
        kwin-wayland
        kwrite
        kwrited
        libpam-kwallet5
        libreoffice-calc
        libreoffice-impress
        libreoffice-kf6
        libreoffice-plasma
        libreoffice-writer
        merkuro
        mpv
        neochat
        nfs-common
        ocean-sound-theme
        okular
        plasma-desktop
        plasma-discover
        plasma-discover-backend-flatpak
        plasma-discover-backend-fwupd
        plasma-disks
        plasma-nm
        plasma-pa
        plasma-systemmonitor
        plasma-welcome
        plasma-workspace-wallpapers
        powerdevil
        print-manager
        sddm
        sddm-theme-breeze
        system-config-printer
        system-config-printer-udev
        tokodon
        transmission
        transmission-qt
        udisks2
        upower
        xdg-desktop-portal-gtk
        xdg-desktop-portal-kde
        xsettings-kde
        yt-dlp

[Validation]
Checksum=yes
