[Match]
Architecture=arm64

[Output]
Format=tar
ImageId=fex-emu-build
Output=%i_%v_%a
ManifestFormat=json

[Content]
Bootable=no
Packages=
        binfmt-support
        ccache
        clang
        cmake
        g++-x86-64-linux-gnu
        git
        libc-bin
        libc6-dev-i386-amd64-cross
        lib32stdc++-14-dev-amd64-cross
        libgcc-14-dev-amd64-cross
        libgcc-14-dev-i386-cross
        libssl-dev
        libstdc++-12-dev-amd64-cross
        libstdc++-12-dev-arm64-cross
        libstdc++-12-dev-i386-cross
        lld
        llvm
        nasm
        ninja-build
        pkgconf
        python3-clang
        python3-setuptools
        qtdeclarative6-dev
        qml6-module-qtquick-controls
        qml6-module-qtquick-dialogs
        qml6-module-qtquick-layouts
        qml6-module-qtqml-workerscript
        qml6-module-qtquick-templates
        qml6-module-qtquick-window
        squashfs-tools
        squashfuse

[Validation]
Checksum=yes
