[Output]
Format=sysext
ImageId=llamacpp
ManifestFormat=json
Output=%i_%v_%a
Overlay=yes

[Content]
BaseTrees=%O/base_%v_%a
Packages=
        libggml0-backend-cpu
        libggml0-backend-hip
        libggml0-backend-vulkan
        llama.cpp

[Validation]
Checksum=yes
