name: Build output artifacts

on:
  push:
    branches:
    - sid
  workflow_dispatch:    # Allows manual triggering

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.host }}

    steps:
      - name: Update repositories
        run: |
          sudo apt -y update

      - name: Install mkosi
        uses: systemd/mkosi@v26

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the image
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_KEY" --output mkosi.key mkosi.key.gpg
          chmod 700 mkosi.key
          gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_KEY" --output mkosi.crt mkosi.crt.gpg
          chmod 700 mkosi.crt
          mkosi build --force
          rm mkosi.key
          rm mkosi.crt
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false     
          path: mkosi.output/*
          retention-days: 7
