name: Build output artifacts

on:
  push:
    branches:
    - sid
  workflow_dispatch:    # Allows manual triggering

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.host }}

    steps:
      - name: Update repositories
        run: |
          sudo apt -y update

      - name: Install mkosi
        uses: systemd/mkosi@v26

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Build the image
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_KEY" --output mkosi.key mkosi.key.gpg
          chmod 700 mkosi.key
          gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_KEY" --output mkosi.crt mkosi.crt.gpg
          chmod 700 mkosi.crt
          mkosi build --force
          rm mkosi.key
          rm mkosi.crt
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false     
          if-no-files-found: ignore
          path: mkosi.output/base_*_arm64.tar.zst
          retention-days: 7
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false     
          if-no-files-found: ignore
          path: mkosi.output/base_*_arm64.manifest
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false     
          if-no-files-found: ignore
          path: mkosi.output/base_*_x86-64.tar.zst
          retention-days: 7
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false     
          if-no-files-found: ignore
          path: mkosi.output/base_*_x86-64.manifest
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false     
          if-no-files-found: ignore
          path: mkosi.output/charon_*_arm64.raw
          retention-days: 7
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false     
          if-no-files-found: ignore
          path: mkosi.output/charon_*_arm64.usr-arm64.*.raw
          retention-days: 7
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false     
          if-no-files-found: ignore
          path: mkosi.output/charon_*_arm64.usr-arm64-verity.*.raw
          retention-days: 7
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false     
          if-no-files-found: ignore
          path: mkosi.output/charon_*_arm64.usr-arm64-verity-sig.*.raw
          retention-days: 7
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false  
          if-no-files-found: ignore   
          path: mkosi.output/juno_*_x86-64.raw
          retention-days: 7
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false     
          if-no-files-found: ignore
          path: mkosi.output/juno_*_x86-64.usr-x86-64.*.raw
          retention-days: 7
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false     
          if-no-files-found: ignore
          path: mkosi.output/juno_*_x86-64.usr-x86-64-verity.*.raw
          retention-days: 7
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false     
          if-no-files-found: ignore
          path: mkosi.output/juno_*_x86-64.usr-x86-64-verity-sig.*.raw
          retention-days: 7
