name: Build output artifacts

on:
  push:
    branches:
    - sid
  workflow_dispatch:    # Allows manual triggering

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        host: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.host }}

    steps:
      - name: Install mkosi
        uses: systemd/mkosi@v26

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the image
        run: |
          mkosi build --force

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: mkosi.outputs/*
      
