name: Build ArchLinux Image for "juno"

on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 3 * * *' # Every day at 3 AM UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          apt update -y
          apt install -y pacman mkosi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the image
        run: |
          mkosi --distribution arch --force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-image
          path: mkosi.output/
