name: Build ArchLinux Image for "juno"

on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 3 * * *' # Every day at 3 AM UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt update --assume-yes
          sudo apt-get install --assume-yes --no-install-recommends archlinux-keyring pacman pacman-package-manager makepkg mkosi systemd-ukify

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show image summary
        run: mkosi summary

      - name: Initialize pacman keyring
        run: |
          sudo pacman-key --init
          sudo pacman-key --populate archlinux
          sudo pacman-key --refresh-keys

      - name: Build the image
        run: |
          sudo mkosi --distribution arch --force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-image
          path: mkosi.output/
